### ISSUE TITLE
Homeserver freezes indefinitely when KWL power is cut when integration enabled

### ISSUE THREAD

**Issue by zsolth** [frawe/EasyControls3_homeassistant#3] opened 2024-10-21 22:01 UTC
Hi, I've noticed a weird and mildly annoying issue while testing a zigbee smart plug for measuring / controlling power to my KWL500. Apparently if you cut the power to the KWL while your integration is enabled, HA becomes completely unresponsive.

First I though it's a zigbee issue, but after disabling your plugin I had no issues whatsoever with cutting power to KWL. 

After re-enabling the plugin I could 100% reproduce the issue (plugging power from KWL kills HA)

Also:
- Plugging KWL back instantly fixes HA 
- SSH addon remains responsive (both existing session and I can even start another session)
- I've tried both the relatively recent version 1.2 and 1.1.1 as well (using HACS)

Version:
  OS Version:               Home Assistant OS 13.2
  Home Assistant Core:      2024.10.3

Unfortunately I've not spotted anything odd in logs, but if you have an idea where to check, I could take a look around

And thanks again for the work, your integration is still super-usefull otherwise

**Comment by frawe** [comment] 2024-10-22 07:30
ok, I will take a look into that... at the moment i have no real idea what could cause that.

**Comment by zsolth** [comment] 2024-10-28 13:02
Oddly enough, the issue seems to be resolved by https://github.com/frawe/EasyControls3_homeassistant/pull/6, though I only have emirical evidence, it wasn't the intention, just wanted to remove obvious error message before trying to do some further debugging of this issue

Hope I didn't just jinx it...

**Comment by zsolth** [comment] 2024-10-28 13:45
Obviously, I did jinx it. Tested a few times, sometimes turning off the KWL didn't cause any issues, then eventually it did make HA unresponsive. With that said, my log is still updating every now-and-then

```
2024-10-28 14:35:05.634 DEBUG (MainThread) [custom_components.EasyControls3_homeassistant.EasyControls3Instance] sent
2024-10-28 14:36:05.668 DEBUG (MainThread) [custom_components.EasyControls3_homeassistant.EasyControls3Instance] connected
2024-10-28 14:36:05.669 DEBUG (MainThread) [custom_components.EasyControls3_homeassistant.EasyControls3Instance] sent
2024-10-28 14:37:05.706 DEBUG (MainThread) [custom_components.EasyControls3_homeassistant.EasyControls3Instance] connected
2024-10-28 14:37:05.710 DEBUG (MainThread) [custom_components.EasyControls3_homeassistant.EasyControls3Instance] sent
2024-10-28 14:38:15.736 ERROR (MainThread) [custom_components.EasyControls3_homeassistant.EasyControls3Instance] error in reading (timed out)
2024-10-28 14:38:33.005 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection] [139818816146736] Unexpected exception
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 245, in handle_call_service
    response = await hass.services.async_call(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 2761, in async_call
    response_data = await coro
                    ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 2804, in _execute_service
    return await target(service_call)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 996, in entity_service_call
    single_response = await _handle_entity_call(
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 1068, in _handle_entity_call
    result = await task
             ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/select/__init__.py", line 188, in async_handle_select_option
    await self.async_select_option(option)
  File "/config/custom_components/EasyControls3_homeassistant/select.py", line 33, in async_select_option
    await self._easyConnector.switchMode(KWLState[option])
  File "/config/custom_components/EasyControls3_homeassistant/EasyControls3Instance.py", line 159, in switchMode
    response = await self._exchangeData(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/EasyControls3_homeassistant/EasyControls3Instance.py", line 41, in _exchangeData
    with connect(self._url) as websocket:
         ^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/websockets/sync/client.py", line 247, in connect
    sock = socket.create_connection(
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/socket.py", line 853, in create_connection
    raise exceptions[0]
  File "/usr/local/lib/python3.12/socket.py", line 838, in create_connection
    sock.connect(sa)
TimeoutError: timed out
2024-10-28 14:39:15.596 ERROR (MainThread) [custom_components.EasyControls3_homeassistant.EasyControls3Instance] error in reading (timed out)
2024-10-28 14:39:25.644 ERROR (MainThread) [custom_components.EasyControls3_homeassistant.EasyControls3Instance] error in reading (timed out)
2024-10-28 14:39:35.651 ERROR (MainThread) [custom_components.EasyControls3_homeassistant.EasyControls3Instance] error in reading (timed out)
2024-10-28 14:39:45.654 ERROR (MainThread) [custom_components.EasyControls3_homeassistant.EasyControls3Instance] error in reading (timed out)
2024-10-28 14:39:55.663 ERROR (MainThread) [custom_components.EasyControls3_homeassistant.EasyControls3Instance] error in reading (timed out)
2024-10-28 14:40:05.673 ERROR (MainThread) [custom_components.EasyControls3_homeassistant.EasyControls3Instance] error in reading (timed out)
2024-10-28 14:40:15.680 ERROR (MainThread) [custom_components.EasyControls3_homeassistant.EasyControls3Instance] error in reading (timed out)
2024-10-28 14:40:25.691 ERROR (MainThread) [custom_components.EasyControls3_homeassistant.EasyControls3Instance] error in reading (timed out)
2024-10-28 14:40:35.702 ERROR (MainThread) [custom_components.EasyControls3_homeassistant.EasyControls3Instance] error in reading (timed out)
2024-10-28 14:40:45.714 ERROR (MainThread) [custom_components.EasyControls3_homeassistant.EasyControls3Instance] error in reading (timed out)
2024-10-28 14:40:55.725 ERROR (MainThread) [custom_components.EasyControls3_homeassistant.EasyControls3Instance] error in reading (timed out)
2024-10-28 14:41:05.731 ERROR (MainThread) [custom_components.EasyControls3_homeassistant.EasyControls3Instance] error in reading (timed out)
```

**Comment by zsolth** [comment] 2024-10-28 17:21
Did some extra debugging, results are below:

```
2024-10-28 17:45:13.906 DEBUG (MainThread) [custom_components.EasyControls3_homeassistant.EasyControls3Instance] before connect
2024-10-28 17:45:13.923 DEBUG (MainThread) [custom_components.EasyControls3_homeassistant.EasyControls3Instance] connected
2024-10-28 17:45:13.924 DEBUG (MainThread) [custom_components.EasyControls3_homeassistant.EasyControls3Instance] sent
2024-10-28 17:46:13.946 DEBUG (MainThread) [custom_components.EasyControls3_homeassistant.EasyControls3Instance] before connect
2024-10-28 17:46:13.962 DEBUG (MainThread) [custom_components.EasyControls3_homeassistant.EasyControls3Instance] connected
2024-10-28 17:46:13.962 DEBUG (MainThread) [custom_components.EasyControls3_homeassistant.EasyControls3Instance] sent
2024-10-28 17:47:13.987 DEBUG (MainThread) [custom_components.EasyControls3_homeassistant.EasyControls3Instance] before connect
2024-10-28 17:47:14.002 DEBUG (MainThread) [custom_components.EasyControls3_homeassistant.EasyControls3Instance] connected
2024-10-28 17:47:14.003 DEBUG (MainThread) [custom_components.EasyControls3_homeassistant.EasyControls3Instance] sent
2024-10-28 17:48:14.025 DEBUG (MainThread) [custom_components.EasyControls3_homeassistant.EasyControls3Instance] before connect
2024-10-28 17:48:14.042 DEBUG (MainThread) [custom_components.EasyControls3_homeassistant.EasyControls3Instance] connected
2024-10-28 17:48:14.042 DEBUG (MainThread) [custom_components.EasyControls3_homeassistant.EasyControls3Instance] sent
2024-10-28 17:49:14.060 DEBUG (MainThread) [custom_components.EasyControls3_homeassistant.EasyControls3Instance] before connect
2024-10-28 17:49:14.077 DEBUG (MainThread) [custom_components.EasyControls3_homeassistant.EasyControls3Instance] connected
2024-10-28 17:49:14.078 DEBUG (MainThread) [custom_components.EasyControls3_homeassistant.EasyControls3Instance] sent
2024-10-28 17:51:13.912 DEBUG (MainThread) [custom_components.EasyControls3_homeassistant.EasyControls3Instance] before connect
2024-10-28 17:51:13.927 DEBUG (MainThread) [custom_components.EasyControls3_homeassistant.EasyControls3Instance] connected
2024-10-28 17:51:13.928 DEBUG (MainThread) [custom_components.EasyControls3_homeassistant.EasyControls3Instance] sent
2024-10-28 17:52:13.951 DEBUG (MainThread) [custom_components.EasyControls3_homeassistant.EasyControls3Instance] before connect
2024-10-28 17:52:13.967 DEBUG (MainThread) [custom_components.EasyControls3_homeassistant.EasyControls3Instance] connected
2024-10-28 17:52:13.968 DEBUG (MainThread) [custom_components.EasyControls3_homeassistant.EasyControls3Instance] sent
2024-10-28 17:53:13.992 DEBUG (MainThread) [custom_components.EasyControls3_homeassistant.EasyControls3Instance] before connect
2024-10-28 17:53:14.008 DEBUG (MainThread) [custom_components.EasyControls3_homeassistant.EasyControls3Instance] connected
2024-10-28 17:53:14.009 DEBUG (MainThread) [custom_components.EasyControls3_homeassistant.EasyControls3Instance] sent
2024-10-28 17:54:14.033 DEBUG (MainThread) [custom_components.EasyControls3_homeassistant.EasyControls3Instance] before connect
2024-10-28 17:54:14.049 DEBUG (MainThread) [custom_components.EasyControls3_homeassistant.EasyControls3Instance] connected
2024-10-28 17:54:14.049 DEBUG (MainThread) [custom_components.EasyControls3_homeassistant.EasyControls3Instance] sent
2024-10-28 17:55:14.069 DEBUG (MainThread) [custom_components.EasyControls3_homeassistant.EasyControls3Instance] before connect
2024-10-28 17:55:14.085 DEBUG (MainThread) [custom_components.EasyControls3_homeassistant.EasyControls3Instance] connected
2024-10-28 17:55:14.085 DEBUG (MainThread) [custom_components.EasyControls3_homeassistant.EasyControls3Instance] sent
-- KWL unplugged, HA becoming unresponsive after a few seconds
...
-- KWL re-plugged again, HA becomes responsive again, and (apparently) also dumps messages to error log (though I believe most actually belong to the time period KWL unplugged / re-plugged
2024-10-28 17:57:13.917 DEBUG (MainThread) [custom_components.EasyControls3_homeassistant.EasyControls3Instance] before connect
2024-10-28 17:57:23.928 ERROR (MainThread) [custom_components.EasyControls3_homeassistant.EasyControls3Instance] error in reading (timed out)
2024-10-28 17:57:23.957 DEBUG (MainThread) [custom_components.EasyControls3_homeassistant.EasyControls3Instance] before connect
2024-10-28 17:57:33.966 ERROR (MainThread) [custom_components.EasyControls3_homeassistant.EasyControls3Instance] error in reading (timed out)
2024-10-28 17:57:33.967 DEBUG (MainThread) [custom_components.EasyControls3_homeassistant.EasyControls3Instance] before connect
2024-10-28 17:57:43.975 ERROR (MainThread) [custom_components.EasyControls3_homeassistant.EasyControls3Instance] error in reading (timed out)
2024-10-28 17:57:43.975 DEBUG (MainThread) [custom_components.EasyControls3_homeassistant.EasyControls3Instance] before connect
2024-10-28 17:57:53.987 ERROR (MainThread) [custom_components.EasyControls3_homeassistant.EasyControls3Instance] error in reading (timed out)
2024-10-28 17:57:53.987 DEBUG (MainThread) [custom_components.EasyControls3_homeassistant.EasyControls3Instance] before connect
2024-10-28 17:58:03.999 ERROR (MainThread) [custom_components.EasyControls3_homeassistant.EasyControls3Instance] error in reading (timed out)
2024-10-28 17:58:03.999 DEBUG (MainThread) [custom_components.EasyControls3_homeassistant.EasyControls3Instance] before connect
2024-10-28 17:58:14.009 ERROR (MainThread) [custom_components.EasyControls3_homeassistant.EasyControls3Instance] error in reading (timed out)
2024-10-28 17:58:14.010 DEBUG (MainThread) [custom_components.EasyControls3_homeassistant.EasyControls3Instance] before connect
2024-10-28 17:58:24.020 ERROR (MainThread) [custom_components.EasyControls3_homeassistant.EasyControls3Instance] error in reading (timed out)
2024-10-28 17:58:24.021 DEBUG (MainThread) [custom_components.EasyControls3_homeassistant.EasyControls3Instance] before connect
2024-10-28 17:58:34.032 ERROR (MainThread) [custom_components.EasyControls3_homeassistant.EasyControls3Instance] error in reading (timed out)
2024-10-28 17:58:34.032 DEBUG (MainThread) [custom_components.EasyControls3_homeassistant.EasyControls3Instance] before connect
2024-10-28 17:58:39.157 ERROR (MainThread) [custom_components.EasyControls3_homeassistant.EasyControls3Instance] error in reading ([Errno 111] Connection refused)
2024-10-28 17:58:39.158 DEBUG (MainThread) [custom_components.EasyControls3_homeassistant.EasyControls3Instance] before connect
2024-10-28 17:58:39.160 ERROR (MainThread) [custom_components.EasyControls3_homeassistant.EasyControls3Instance] error in reading ([Errno 111] Connection refused)
2024-10-28 17:58:39.160 DEBUG (MainThread) [custom_components.EasyControls3_homeassistant.EasyControls3Instance] before connect
2024-10-28 17:58:39.162 ERROR (MainThread) [custom_components.EasyControls3_homeassistant.EasyControls3Instance] error in reading ([Errno 111] Connection refused)
2024-10-28 17:58:39.163 DEBUG (MainThread) [custom_components.EasyControls3_homeassistant.EasyControls3Instance] before connect
2024-10-28 17:58:39.166 ERROR (MainThread) [custom_components.EasyControls3_homeassistant.EasyControls3Instance] error in reading ([Errno 111] Connection refused)
2024-10-28 17:58:39.349 DEBUG (MainThread) [custom_components.EasyControls3_homeassistant.EasyControls3Instance] before connect
2024-10-28 17:58:39.351 ERROR (MainThread) [custom_components.EasyControls3_homeassistant.EasyControls3Instance] error in reading ([Errno 111] Connection refused)
2024-10-28 17:58:39.352 DEBUG (MainThread) [custom_components.EasyControls3_homeassistant.EasyControls3Instance] before connect
2024-10-28 17:58:39.357 ERROR (MainThread) [custom_components.EasyControls3_homeassistant.EasyControls3Instance] error in reading ([Errno 111] Connection refused)
2024-10-28 17:58:39.357 DEBUG (MainThread) [custom_components.EasyControls3_homeassistant.EasyControls3Instance] before connect
2024-10-28 17:58:39.359 ERROR (MainThread) [custom_components.EasyControls3_homeassistant.EasyControls3Instance] error in reading ([Errno 111] Connection refused)
2024-10-28 17:58:39.359 DEBUG (MainThread) [custom_components.EasyControls3_homeassistant.EasyControls3Instance] before connect
2024-10-28 17:58:39.360 ERROR (MainThread) [custom_components.EasyControls3_homeassistant.EasyControls3Instance] error in reading ([Errno 111] Connection refused)
2024-10-28 17:58:39.361 DEBUG (MainThread) [custom_components.EasyControls3_homeassistant.EasyControls3Instance] before connect
2024-10-28 17:58:39.362 ERROR (MainThread) [custom_components.EasyControls3_homeassistant.EasyControls3Instance] error in reading ([Errno 111] Connection refused)
2024-10-28 17:58:39.362 DEBUG (MainThread) [custom_components.EasyControls3_homeassistant.EasyControls3Instance] before connect
2024-10-28 17:58:39.364 ERROR (MainThread) [custom_components.EasyControls3_homeassistant.EasyControls3Instance] error in reading ([Errno 111] Connection refused)
2024-10-28 17:58:39.364 DEBUG (MainThread) [custom_components.EasyControls3_homeassistant.EasyControls3Instance] before connect
2024-10-28 17:58:39.365 ERROR (MainThread) [custom_components.EasyControls3_homeassistant.EasyControls3Instance] error in reading ([Errno 111] Connection refused)
2024-10-28 17:58:39.365 DEBUG (MainThread) [custom_components.EasyControls3_homeassistant.EasyControls3Instance] before connect
2024-10-28 17:58:39.367 ERROR (MainThread) [custom_components.EasyControls3_homeassistant.EasyControls3Instance] error in reading ([Errno 111] Connection refused)
2024-10-28 17:58:39.367 DEBUG (MainThread) [custom_components.EasyControls3_homeassistant.EasyControls3Instance] before connect
2024-10-28 17:58:39.369 ERROR (MainThread) [custom_components.EasyControls3_homeassistant.EasyControls3Instance] error in reading ([Errno 111] Connection refused)
2024-10-28 17:58:39.369 DEBUG (MainThread) [custom_components.EasyControls3_homeassistant.EasyControls3Instance] before connect
2024-10-28 17:58:39.370 ERROR (MainThread) [custom_components.EasyControls3_homeassistant.EasyControls3Instance] error in reading ([Errno 111] Connection refused)
2024-10-28 17:59:39.162 DEBUG (MainThread) [custom_components.EasyControls3_homeassistant.EasyControls3Instance] before connect
2024-10-28 17:59:39.177 DEBUG (MainThread) [custom_components.EasyControls3_homeassistant.EasyControls3Instance] connected
2024-10-28 17:59:39.178 DEBUG (MainThread) [custom_components.EasyControls3_homeassistant.EasyControls3Instance] sent

```

**Comment by zsolth** [comment] 2024-10-28 17:24
The "before connect part" is just something I added to _exchangeData to see where things start to get blocked, and interestingly it's not during the connection (and/or the debug message is also processed in an async manner)

```
async def _exchangeData(self, request):
        LOGGER.debug("before connect")
        with connect(self._url) as websocket:
            LOGGER.debug("connected")

            # request current data package
            websocket.send(request)
            LOGGER.debug("sent")

            return websocket.recv()
```

**Comment by zsolth** [comment] 2024-10-28 19:48
FYI, I have a WIP fix using websockets.asyncio.client that now seems to properly be able to deal with KWL not being available producing output like this during physical device being down (with HA staying responsive):

```
2024-10-28 20:42:51.339 DEBUG (MainThread) [custom_components.EasyControls3_homeassistant.EasyControls3Instance] sent
2024-10-28 20:42:51.361 DEBUG (MainThread) [custom_components.EasyControls3_homeassistant.EasyControls3Instance] connected
2024-10-28 20:42:51.362 DEBUG (MainThread) [custom_components.EasyControls3_homeassistant.EasyControls3Instance] sent
2024-10-28 20:42:51.381 DEBUG (MainThread) [custom_components.EasyControls3_homeassistant.EasyControls3Instance] connected
2024-10-28 20:42:51.382 DEBUG (MainThread) [custom_components.EasyControls3_homeassistant.EasyControls3Instance] sent
2024-10-28 20:43:51.401 INFO (MainThread) [custom_components.EasyControls3_homeassistant.EasyControls3Instance] readCurrentData
2024-10-28 20:43:51.402 DEBUG (MainThread) [custom_components.EasyControls3_homeassistant.EasyControls3Instance] before connect
2024-10-28 20:44:01.403 WARNING (MainThread) [homeassistant.helpers.entity] Update of switch.kwl_on_off_switch is taking over 10 seconds
2024-10-28 20:44:01.404 ERROR (MainThread) [custom_components.EasyControls3_homeassistant.EasyControls3Instance] error in reading (timed out during handshake)
2024-10-28 20:44:51.317 INFO (MainThread) [custom_components.EasyControls3_homeassistant.EasyControls3Instance] readCurrentData
2024-10-28 20:44:51.317 DEBUG (MainThread) [custom_components.EasyControls3_homeassistant.EasyControls3Instance] before connect
2024-10-28 20:44:51.338 INFO (MainThread) [custom_components.EasyControls3_homeassistant.EasyControls3Instance] readCurrentData
2024-10-28 20:44:51.338 DEBUG (MainThread) [custom_components.EasyControls3_homeassistant.EasyControls3Instance] before connect
2024-10-28 20:44:51.361 INFO (MainThread) [custom_components.EasyControls3_homeassistant.EasyControls3Instance] readCurrentData
2024-10-28 20:44:51.361 DEBUG (MainThread) [custom_components.EasyControls3_homeassistant.EasyControls3Instance] before connect
2024-10-28 20:44:51.362 INFO (MainThread) [custom_components.EasyControls3_homeassistant.EasyControls3Instance] readCurrentData
2024-10-28 20:44:51.362 DEBUG (MainThread) [custom_components.EasyControls3_homeassistant.EasyControls3Instance] before connect
2024-10-28 20:44:51.363 INFO (MainThread) [custom_components.EasyControls3_homeassistant.EasyControls3Instance] readCurrentData
2024-10-28 20:44:51.363 DEBUG (MainThread) [custom_components.EasyControls3_homeassistant.EasyControls3Instance] before connect
2024-10-28 20:44:51.364 INFO (MainThread) [custom_components.EasyControls3_homeassistant.EasyControls3Instance] readCurrentData
2024-10-28 20:44:51.364 DEBUG (MainThread) [custom_components.EasyControls3_homeassistant.EasyControls3Instance] before connect
2024-10-28 20:44:51.365 INFO (MainThread) [custom_components.EasyControls3_homeassistant.EasyControls3Instance] readCurrentData
2024-10-28 20:44:51.365 DEBUG (MainThread) [custom_components.EasyControls3_homeassistant.EasyControls3Instance] before connect
2024-10-28 20:44:51.383 INFO (MainThread) [custom_components.EasyControls3_homeassistant.EasyControls3Instance] readCurrentData
2024-10-28 20:44:51.383 DEBUG (MainThread) [custom_components.EasyControls3_homeassistant.EasyControls3Instance] before connect
2024-10-28 20:44:51.402 INFO (MainThread) [custom_components.EasyControls3_homeassistant.EasyControls3Instance] readCurrentData
2024-10-28 20:44:51.402 DEBUG (MainThread) [custom_components.EasyControls3_homeassistant.EasyControls3Instance] before connect
2024-10-28 20:45:01.318 WARNING (MainThread) [homeassistant.helpers.entity] Update of number.set_speed_for_intensive_fan is taking over 10 seconds
2024-10-28 20:45:01.318 ERROR (MainThread) [custom_components.EasyControls3_homeassistant.EasyControls3Instance] error in reading (timed out during handshake)
2024-10-28 20:45:01.339 WARNING (MainThread) [homeassistant.helpers.entity] Update of select.select_state_of_the_kwl is taking over 10 seconds
2024-10-28 20:45:01.339 ERROR (MainThread) [custom_components.EasyControls3_homeassistant.EasyControls3Instance] error in reading (timed out during handshake)
2024-10-28 20:45:01.361 WARNING (MainThread) [homeassistant.helpers.entity] Update of sensor.kwl_500_w_l_air_relativ_humidity is taking over 10 seconds
2024-10-28 20:45:01.361 WARNING (MainThread) [homeassistant.helpers.entity] Update of sensor.kwl_500_w_l_outside_temperature is taking over 10 seconds
2024-10-28 20:45:01.362 ERROR (MainThread) [custom_components.EasyControls3_homeassistant.EasyControls3Instance] error in reading (timed out during handshake)
2024-10-28 20:45:01.363 WARNING (MainThread) [homeassistant.helpers.entity] Update of sensor.kwl_500_w_l_supply_temperature is taking over 10 seconds
2024-10-28 20:45:01.364 ERROR (MainThread) [custom_components.EasyControls3_homeassistant.EasyControls3Instance] error in reading (timed out during handshake)
2024-10-28 20:45:01.364 WARNING (MainThread) [homeassistant.helpers.entity] Update of sensor.kwl_500_w_l_indoor_temperature is taking over 10 seconds
2024-10-28 20:45:01.365 WARNING (MainThread) [homeassistant.helpers.entity] Update of sensor.kwl_500_w_l_exhaust_temperature is taking over 10 seconds
2024-10-28 20:45:01.365 ERROR (MainThread) [custom_components.EasyControls3_homeassistant.EasyControls3Instance] error in reading (timed out during handshake)
2024-10-28 20:45:01.366 ERROR (MainThread) [custom_components.EasyControls3_homeassistant.EasyControls3Instance] error in reading (timed out during handshake)
2024-10-28 20:45:01.366 WARNING (MainThread) [homeassistant.helpers.entity] Update of sensor.kwl_500_w_l_current_fan_speed is taking over 10 seconds
2024-10-28 20:45:01.367 ERROR (MainThread) [custom_components.EasyControls3_homeassistant.EasyControls3Instance] error in reading (timed out during handshake)
2024-10-28 20:45:01.367 WARNING (MainThread) [homeassistant.helpers.entity] Update of sensor.kwl_500_w_l_last_filter_change is taking over 10 seconds
2024-10-28 20:45:01.367 WARNING (MainThread) [homeassistant.helpers.entity] Update of sensor.kwl_500_w_l_next_filter_change is taking over 10 seconds
2024-10-28 20:45:01.368 ERROR (MainThread) [custom_components.EasyControls3_homeassistant.EasyControls3Instance] error in reading (timed out during handshake)
2024-10-28 20:45:01.384 WARNING (MainThread) [homeassistant.helpers.entity] Update of time.time_for_the_intensive_mode is taking over 10 seconds
2024-10-28 20:45:01.385 ERROR (MainThread) [custom_components.EasyControls3_homeassistant.EasyControls3Instance] error in reading (timed out during handshake)
2024-10-28 20:45:01.403 WARNING (MainThread) [homeassistant.helpers.entity] Update of switch.kwl_on_off_switch is taking over 10 seconds
2024-10-28 20:45:01.403 ERROR (MainThread) [custom_components.EasyControls3_homeassistant.EasyControls3Instance] error in reading (timed out during handshake)
2024-10-28 20:45:51.319 INFO (MainThread) [custom_components.EasyControls3_homeassistant.EasyControls3Instance] readCurrentData
2024-10-28 20:45:51.319 DEBUG (MainThread) [custom_components.EasyControls3_homeassistant.EasyControls3Instance] before connect
2024-10-28 20:45:51.336 DEBUG (MainThread) [custom_components.EasyControls3_homeassistant.EasyControls3Instance] connected
2024-10-28 20:45:51.337 DEBUG (MainThread) [custom_components.EasyControls3_homeassistant.EasyControls3Instance] sent
2024-10-28 20:45:51.339 INFO (MainThread) [custom_components.EasyControls3_homeassistant.EasyControls3Instance] readCurrentData
2024-10-28 20:45:51.339 DEBUG (MainThread) [custom_components.EasyControls3_homeassistant.EasyControls3Instance] before connect
2024-10-28 20:45:51.365 DEBUG (MainThread) [custom_components.EasyControls3_homeassistant.EasyControls3Instance] connected
2024-10-28 20:45:51.366 DEBUG (MainThread) [custom_components.EasyControls3_homeassistant.EasyControls3Instance] sent
```

I'll be testing this for the next week or so then I'll raise a PR

**Comment by frawe** [comment] 2024-10-28 20:26
i will also look into it and try to find a suliton ;)

**Comment by frawe** [comment] 2024-10-28 21:31
I (sadly) can reproduce your error and was not able to fix it till now 😭 - but it behaves a little different on my system... normally it is working like I expecte (going to unavailabe state after some time), but i also saw times where it didn't do that...

One question that acomes to my mind, why do you use a socket to turn the kwl off, and not just set it to off state (I added that feature already to the current version on github)

And I also was told that the KWL should run always... 

Maybe there is a way to work arount this issue :D

**Comment by frawe** [comment] 2024-10-28 21:35
And btw, you do not need to turn the KWL on and off, plugging in and out the ethernet wire is also fine ;)

**Comment by zsolth** [comment] 2024-10-28 21:37
Created a PR to fix (but I'll keep testing it locally as well for some time). As to why I turn it off, it's really annoying - after a while (4-6 weeks, the KWL simply becomes unavailable via the network. Turning it off an on again solves the issue. Likely something silly in the software running on the KWL, but I don't expect helios to release a fix (or any sort of upgrade) at all :-/

**Comment by zsolth** [comment] 2024-10-28 21:40
https://github.com/frawe/EasyControls3_homeassistant/pull/7 I mean

**Comment by frawe** [comment] 2024-10-30 06:49
ok, that is strange, that your KWL is going "lost"! after some weeks 🤔 

luckily I don't have that problem ;)

But I had a lot problems in the beginning finding it in the net... used some kind of 193.... for my home network and it got an ip and was in the router... but you never could connect to it...

And I think the update the firmeware quite often, but the question is if we really should update, because in the ende the "fix" sth. and then we could not use the integration anymore and need to buy some of there smart home stuff (like knx gateway and license or similar)


By the way just out of curiosity, from which country are you? (german by myself 😉 )

**Comment by zsolth** [comment] 2024-11-01 08:06
FYI, I personally consider the fix I opened the PR for fixed, I've been testing it for the last few days and it seems to be solid, no lock-ups and functionality (both query and fixes, like changing the mode) work nicely

I'm from Hungary btw 

A quick question - which easycontrols 3.0 version are you on? Based on your comment it looks like there's definitely a much newer one available than mine (1.0.9 on a KWL 500), I just want to make sure I'm not breaking integration capabilities by updating to a version that breaks local communication

**Comment by frawe** [comment] 2024-11-03 17:27
ok, will take it in then ;)

i also think i should change the part when self.sthModified is changed back to false (because I think that also could cause problems).

I have the version 1.0.19, from one other issue I think somebody alrady has a newer version tried out..

But I am with you, thea fear that they will change something I could no use the integration anymore is bigger than what I expecte that a new firmware version will offer :D

**Comment by mgrfilipmarek** [comment] 2024-11-04 05:53
FYI: I`m running 1.0.17 sw version on my KWL 360 and with this integrations works perfectly :)
But looks like in newest version 1.0.23, they implemented - "Simple switching off of the unit" (https://www.heliosventilatoren.de/en/easycontrols-update-englisch)

**Comment by frawe** [comment] 2024-11-04 05:59
this simple off switching is already in my version available ^^

it also is possible to do with the current sw on git (is not released so it will not be told over hacs at the moment)

**Comment by frawe** [comment] 2024-11-04 06:19
@zsolth did you also get the following errors?
[custom_components.EasyControls3_homeassistant.EasyControls3Instance] error in reading (connection closed while reading HTTP status line)

**Comment by zsolth** [comment] 2024-11-04 06:34
Yes, I am seeing them, but frankly I don't see any functional problems. My guess is that the kwl is only accepting one connection at a time, and now we might have multiple queries at the same time (due to how HA queries enities). Could probably be fixed by introducing an "isQueryRunning" style variable (I believe you are already doing something after the call was successful but that logic may need to be moved now that the actual http query is not blocking)

**Comment by frawe** [comment] 2024-11-04 06:47
ok, then it is at least the same on your system :D

I will try to fix that before I create a new relase with the fix in it ;)

maybe I need some kind of semaphore to ensure that only one call at a time is made...

but for the moment it at least is not freezing hass anymore^^

**Comment by zsolth** [comment] 2024-11-04 06:55
You could probably use something like what's described here: https://www.perrotta.dev/2024/01/synchronized-in-python/

**Comment by zsolth** [comment] 2024-11-04 08:31
Fyi, I have a POC solution for this using asyncio.Lock, something along the lines of

```

import asyncio
.
.
.
class EasyControls3Instance:
    def __init__(self, url: str) -> None:
        self.lock = asyncio.Lock()
.
.
.
    async def _exchangeData(self, request):
        async with self.lock:
            async with connect(self._url) as websocket:
                LOGGER.debug("connected")
                # request current data package
                await websocket.send(request)
                LOGGER.debug("sent")
                response = await websocket.recv()
                return response

```

I'll be testing this for a few days and will let you know (but the above is literally the only change you need to change, so you can also try yourself...)

**Comment by zsolth** [comment] 2024-11-04 09:10
https://github.com/frawe/EasyControls3_homeassistant/pull/8/files

**Comment by frawe** [comment] 2024-11-08 05:44
I took your PR 😄 

Thank you for it.

I will clean up, update readme and create a new release soon.

I think I also should try to get people to write theire firmeware version to an issue ticket or so... so that people with old versions could check if the can updated securly.

Let me now if you have any additional thoughts, otherwise I would close the issue.

**Comment by zsolth** [comment] 2024-11-08 06:45
Cheers. Firmware query is a great idea! And agreed, I consider the problem solved, so you can close the issue

**Closed as completed** 2024-11-08 07:07 UTC
